theme: jekyll-theme-minimal

title: Yuan Zhou
description: Exciting to start my personal website. 

# logo: [Location of the logo]
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
