theme: jekyll-theme-minimal

title: Yuan Zhou
logo: /assets/img/logo.jpg
# description: Email
site.email: true


show_downloads: false
site.google.scholar: https://scholar.google.co.uk/citations?user=qj8T17gAAAAJ&hl=en

google_analytics: true
theme: jekyll-theme-minimal
